spring.application.name=mentora-bot

#----------------------------------------------------
#	DB CONNECTION
#----------------------------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#----------------------------------------------------
#	TELEGRAM CONFIGURATION
#----------------------------------------------------
telegrambotconnection.service.props.telegramUsername=${TELEGRAM_USERNAME}
telegrambotconnection.service.props.telemgramToken=${TELEGRAM_TOKEN}

#----------------------------------------------------
#	OPENROUTER CONFIGURATION
#----------------------------------------------------
openrouter.service.props.apiUrl=${OPENROUTER_API_URL}
openrouter.service.props.apiKey=${OPENROUTER_API_KEY}
openrouter.service.props.models[0]=${OPENROUTER_MODEL_0}
openrouter.service.props.models[1]=${OPENROUTER_MODEL_1}
openrouter.service.props.models[2]=${OPENROUTER_MODEL_2}
openrouter.service.props.models[3]=${OPENROUTER_MODEL_3}
openrouter.service.props.models[4]=${OPENROUTER_MODEL_4}
openrouter.service.props.models[5]=${OPENROUTER_MODEL_5}